apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartments-api-deployment
  labels:
    app: apartments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apartments-api
  template:
    metadata:
      labels:
        app: apartments-api
    spec:
      containers:
      - name: apartments-api
        image: us.gcr.io/apartments-139902/apartments-api
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: "db-mongodb.default.svc.cluster.local"
          - name: DB_PORT
            value: "27017"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-password
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-database

---

apiVersion: v1
kind: Service
metadata:
  name: apartments-api-svc
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: apartments-api
    
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apartments-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: casa.dixon.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: apartments-api-svc
          servicePort: 5000
