controller:
  kind: Deployment
  
  service:
    type: ClusterIP
    
    # This needs to be the INTERNAL-IP of the Ingress Node (kubectl get nodes)
    externalIPs: 
      - 10.138.15.193

  tolerations:
    - key: "ingress"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"

  nodeSelector:
    ingress: "true"

## Default 404 backend
defaultBackend:

  tolerations:
    - key: "ingress"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"

  nodeSelector:
    ingress: "true"
