apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: "db-mongodb.default.svc.cluster.local"
          - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-username
          - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-password
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "false"
          - name: ME_CONFIG_BASICAUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-username
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongodb-password
          - name: ME_CONFIG_SITE_BASEURL
            value: "/db/"

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: mongo-express

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo-express-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /db
        backend:
          serviceName: mongo-express-svc
          servicePort: 8081
